// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accbase/srv/user/proto/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Captcha              string   `protobuf:"bytes,4,opt,name=captcha,proto3" json:"captcha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8046bbbd389d8dc7, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Authority            string   `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Status               bool     `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8046bbbd389d8dc7, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *LoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type RegisterRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Confirm              string   `protobuf:"bytes,5,opt,name=confirm,proto3" json:"confirm,omitempty"`
	Captcha              string   `protobuf:"bytes,6,opt,name=captcha,proto3" json:"captcha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8046bbbd389d8dc7, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetConfirm() string {
	if m != nil {
		return m.Confirm
	}
	return ""
}

func (m *RegisterRequest) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

type RegisterResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Authority            string   `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Status               bool     `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8046bbbd389d8dc7, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RegisterResponse) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *RegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type AccountRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRequest) Reset()         { *m = AccountRequest{} }
func (m *AccountRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()    {}
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8046bbbd389d8dc7, []int{4}
}

func (m *AccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRequest.Unmarshal(m, b)
}
func (m *AccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRequest.Marshal(b, m, deterministic)
}
func (m *AccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRequest.Merge(m, src)
}
func (m *AccountRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRequest.Size(m)
}
func (m *AccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRequest proto.InternalMessageInfo

func (m *AccountRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AccountResponse struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Authority            string   `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Status               bool     `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountResponse) Reset()         { *m = AccountResponse{} }
func (m *AccountResponse) String() string { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()    {}
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8046bbbd389d8dc7, []int{5}
}

func (m *AccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResponse.Unmarshal(m, b)
}
func (m *AccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResponse.Marshal(b, m, deterministic)
}
func (m *AccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResponse.Merge(m, src)
}
func (m *AccountResponse) XXX_Size() int {
	return xxx_messageInfo_AccountResponse.Size(m)
}
func (m *AccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResponse proto.InternalMessageInfo

func (m *AccountResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *AccountResponse) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *AccountResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AccountResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type UserListRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	PageNum              int32    `protobuf:"varint,3,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize             int32    `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	RoleId               int32    `protobuf:"varint,5,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListRequest) Reset()         { *m = UserListRequest{} }
func (m *UserListRequest) String() string { return proto.CompactTextString(m) }
func (*UserListRequest) ProtoMessage()    {}
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8046bbbd389d8dc7, []int{6}
}

func (m *UserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRequest.Unmarshal(m, b)
}
func (m *UserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRequest.Marshal(b, m, deterministic)
}
func (m *UserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRequest.Merge(m, src)
}
func (m *UserListRequest) XXX_Size() int {
	return xxx_messageInfo_UserListRequest.Size(m)
}
func (m *UserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRequest proto.InternalMessageInfo

func (m *UserListRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserListRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserListRequest) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *UserListRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *UserListRequest) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

type UserListResponse struct {
	List                 []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListResponse) Reset()         { *m = UserListResponse{} }
func (m *UserListResponse) String() string { return proto.CompactTextString(m) }
func (*UserListResponse) ProtoMessage()    {}
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8046bbbd389d8dc7, []int{7}
}

func (m *UserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse.Unmarshal(m, b)
}
func (m *UserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse.Marshal(b, m, deterministic)
}
func (m *UserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse.Merge(m, src)
}
func (m *UserListResponse) XXX_Size() int {
	return xxx_messageInfo_UserListResponse.Size(m)
}
func (m *UserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse proto.InternalMessageInfo

func (m *UserListResponse) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *UserListResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "user.LoginResponse")
	proto.RegisterType((*RegisterRequest)(nil), "user.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "user.RegisterResponse")
	proto.RegisterType((*AccountRequest)(nil), "user.AccountRequest")
	proto.RegisterType((*AccountResponse)(nil), "user.AccountResponse")
	proto.RegisterType((*UserListRequest)(nil), "user.UserListRequest")
	proto.RegisterType((*UserListResponse)(nil), "user.UserListResponse")
}

func init() { proto.RegisterFile("accbase/srv/user/proto/user.proto", fileDescriptor_8046bbbd389d8dc7) }

var fileDescriptor_8046bbbd389d8dc7 = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xdf, 0x6a, 0xd4, 0x40,
	0x14, 0xc6, 0x1b, 0x9b, 0x6c, 0x77, 0x0f, 0xea, 0x96, 0x71, 0x5b, 0xc2, 0xe2, 0x45, 0xcd, 0x85,
	0xf4, 0xaa, 0x0b, 0xf5, 0x46, 0x10, 0x04, 0x2f, 0x85, 0xd2, 0x8b, 0x11, 0x1f, 0x60, 0x36, 0x3d,
	0xa6, 0x83, 0x9b, 0x4c, 0x9c, 0x33, 0xd1, 0x2a, 0xf8, 0x14, 0x3e, 0x86, 0xef, 0xe6, 0x33, 0xc8,
	0xfc, 0xcb, 0x6e, 0xc2, 0x22, 0x82, 0xd2, 0xbb, 0xf3, 0x9d, 0xcc, 0x9c, 0xdf, 0x99, 0xef, 0xcc,
	0x04, 0x9e, 0x89, 0xb2, 0x5c, 0x0b, 0xc2, 0x15, 0xe9, 0xcf, 0xab, 0x8e, 0x50, 0xaf, 0x5a, 0xad,
	0x8c, 0x72, 0xe1, 0x85, 0x0b, 0x59, 0x6a, 0xe3, 0xe2, 0x0e, 0x1e, 0x5e, 0xa9, 0x4a, 0x36, 0x1c,
	0x3f, 0x75, 0x48, 0x86, 0x2d, 0x61, 0x6a, 0xf3, 0xd7, 0xa2, 0xc6, 0x3c, 0x39, 0x4b, 0xce, 0x67,
	0xbc, 0xd7, 0xec, 0x14, 0x26, 0xb5, 0x5a, 0xcb, 0x0d, 0xe6, 0x0f, 0xdc, 0x97, 0xa0, 0xec, 0x9e,
	0x56, 0x10, 0x7d, 0x51, 0xfa, 0x26, 0x3f, 0xf4, 0x7b, 0xa2, 0x66, 0x39, 0x1c, 0x95, 0xa2, 0x35,
	0xe5, 0xad, 0xc8, 0x53, 0xf7, 0x29, 0xca, 0xa2, 0x83, 0x47, 0x81, 0x4c, 0xad, 0x6a, 0x08, 0xd9,
	0x02, 0x32, 0xa3, 0x3e, 0x62, 0x13, 0xb8, 0x5e, 0xb0, 0xa7, 0x30, 0x13, 0x9d, 0xb9, 0x55, 0x5a,
	0x9a, 0xaf, 0x81, 0xbb, 0x4d, 0xd8, 0xf2, 0x35, 0x12, 0x89, 0x0a, 0x03, 0x39, 0x4a, 0xdb, 0x2c,
	0x19, 0x61, 0x3a, 0x72, 0xdc, 0x29, 0x0f, 0xaa, 0xf8, 0x99, 0xc0, 0x9c, 0x63, 0x25, 0xc9, 0xa0,
	0xfe, 0x97, 0x43, 0x2f, 0x20, 0xc3, 0x5a, 0xc8, 0x4d, 0xe0, 0x7a, 0x31, 0xb0, 0x22, 0xdd, 0x63,
	0x85, 0x6a, 0x3e, 0x48, 0x5d, 0xe7, 0x59, 0xb0, 0xc2, 0xcb, 0x5d, 0x93, 0x26, 0x43, 0x93, 0xee,
	0xe0, 0x78, 0xdb, 0xec, 0xbd, 0xfa, 0xf4, 0x1c, 0x1e, 0xbf, 0x29, 0x4b, 0xd5, 0x35, 0x26, 0xba,
	0xb4, 0x97, 0x5b, 0x7c, 0x87, 0x79, 0xbf, 0x2e, 0x34, 0xf8, 0x27, 0x3b, 0xff, 0x77, 0x9b, 0x3f,
	0x12, 0x98, 0xbf, 0x27, 0xd4, 0x57, 0x92, 0xcc, 0x5f, 0x8e, 0x33, 0xd4, 0xb1, 0xf0, 0x2c, 0xd6,
	0xb1, 0xe4, 0x56, 0x54, 0x78, 0xdd, 0xd5, 0x8e, 0x9c, 0xf1, 0x28, 0xfd, 0x48, 0x2b, 0x7c, 0x27,
	0xbf, 0xa1, 0x63, 0x67, 0xbc, 0xd7, 0xb6, 0x9a, 0x56, 0x1b, 0x7c, 0x7b, 0xe3, 0x26, 0x9a, 0xf1,
	0xa0, 0x8a, 0xd7, 0x70, 0xbc, 0x6d, 0x2a, 0xb8, 0xc2, 0x20, 0xdd, 0x48, 0x32, 0x79, 0x72, 0x76,
	0x78, 0x3e, 0xe3, 0x2e, 0x1e, 0x75, 0xd3, 0x9f, 0xea, 0xf2, 0x57, 0x02, 0xa9, 0x2d, 0xc0, 0x2e,
	0x21, 0x73, 0x8f, 0x84, 0xb1, 0x0b, 0xf7, 0x74, 0x77, 0xdf, 0xea, 0xf2, 0xc9, 0x20, 0xe7, 0x31,
	0xc5, 0x01, 0x7b, 0x05, 0xd3, 0x78, 0x67, 0xd8, 0x89, 0x5f, 0x32, 0xba, 0xf0, 0xcb, 0xd3, 0x71,
	0xba, 0xdf, 0xfc, 0x12, 0x8e, 0xc2, 0x38, 0xd9, 0xc2, 0x2f, 0x1a, 0xde, 0x82, 0xe5, 0xc9, 0x28,
	0xbb, 0x8b, 0x8d, 0x67, 0x8e, 0xd8, 0xd1, 0x60, 0x22, 0x76, 0x6c, 0x4d, 0x71, 0xb0, 0x9e, 0xb8,
	0x7f, 0xd2, 0x8b, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x32, 0xe2, 0x0b, 0xb8, 0x04, 0x00,
	0x00,
}
