// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accbase/srv/user/proto/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Captcha              string   `protobuf:"bytes,4,opt,name=captcha,proto3" json:"captcha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8046bbbd389d8dc7, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Authority            string   `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8046bbbd389d8dc7, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

type RegisterRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Confirm              string   `protobuf:"bytes,4,opt,name=confirm,proto3" json:"confirm,omitempty"`
	Captcha              string   `protobuf:"bytes,5,opt,name=captcha,proto3" json:"captcha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8046bbbd389d8dc7, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetConfirm() string {
	if m != nil {
		return m.Confirm
	}
	return ""
}

func (m *RegisterRequest) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

type RegisterResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Authority            string   `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8046bbbd389d8dc7, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RegisterResponse) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "user.LoginResponse")
	proto.RegisterType((*RegisterRequest)(nil), "user.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "user.RegisterResponse")
}

func init() { proto.RegisterFile("accbase/srv/user/proto/user.proto", fileDescriptor_8046bbbd389d8dc7) }

var fileDescriptor_8046bbbd389d8dc7 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x15, 0x85, 0xda, 0x4e, 0x34, 0x9a, 0xb1, 0x36, 0x84, 0x78, 0x50, 0x4e, 0x9e, 0x4a, 0x52,
	0x8f, 0x1e, 0x4d, 0x3c, 0x19, 0x0f, 0x24, 0x7e, 0xc0, 0x82, 0x63, 0xbb, 0xb1, 0xb0, 0xb8, 0xb3,
	0x58, 0xfd, 0x0a, 0x7f, 0xd9, 0xb0, 0x0b, 0xa5, 0xf4, 0x62, 0xe2, 0x6d, 0xde, 0x1b, 0x86, 0xf7,
	0xde, 0xcc, 0xc2, 0x8d, 0xc8, 0xf3, 0x4c, 0x30, 0x25, 0xac, 0x3f, 0x93, 0x9a, 0x49, 0x27, 0x95,
	0x56, 0x46, 0xd9, 0x72, 0x6e, 0x4b, 0xf4, 0x9b, 0x3a, 0xfe, 0x82, 0x93, 0x27, 0xb5, 0x94, 0x65,
	0x4a, 0x1f, 0x35, 0xb1, 0xc1, 0x08, 0xc6, 0x0d, 0xff, 0x2c, 0x0a, 0x0a, 0xbd, 0x6b, 0xef, 0x76,
	0x92, 0x6e, 0x31, 0xce, 0x60, 0x54, 0xa8, 0x4c, 0xae, 0x29, 0x3c, 0xb4, 0x9d, 0x16, 0x35, 0x33,
	0x95, 0x60, 0xde, 0x28, 0xfd, 0x1a, 0x1e, 0xb9, 0x99, 0x0e, 0x63, 0x08, 0xc7, 0xb9, 0xa8, 0x4c,
	0xbe, 0x12, 0xa1, 0x6f, 0x5b, 0x1d, 0x8c, 0x1f, 0xe0, 0xb4, 0x55, 0xe6, 0x4a, 0x95, 0x4c, 0x38,
	0x85, 0xc0, 0xa8, 0x77, 0x2a, 0x5b, 0x5d, 0x07, 0xf0, 0x0a, 0x26, 0xa2, 0x36, 0x2b, 0xa5, 0xa5,
	0xf9, 0x6e, 0x75, 0x7b, 0x22, 0xfe, 0xf1, 0xe0, 0x2c, 0xa5, 0xa5, 0x64, 0x43, 0xba, 0x8b, 0xd0,
	0xdb, 0xf4, 0x06, 0x36, 0xa7, 0x10, 0x50, 0x21, 0xe4, 0xba, 0xfd, 0x8b, 0x03, 0x7f, 0x9a, 0x57,
	0xe5, 0x9b, 0xd4, 0xc5, 0xd6, 0xbc, 0x83, 0xbb, 0xb1, 0x82, 0x61, 0xac, 0x47, 0x38, 0xef, 0x0d,
	0xfd, 0x3f, 0xd9, 0x62, 0x03, 0xfe, 0x0b, 0x93, 0xc6, 0x05, 0x04, 0x76, 0x4d, 0x88, 0x73, 0x7b,
	0xbc, 0xdd, 0x6b, 0x45, 0x17, 0x03, 0xce, 0xa9, 0xc5, 0x07, 0x78, 0x0f, 0xe3, 0xce, 0x03, 0x5e,
	0xba, 0x4f, 0xf6, 0x96, 0x14, 0xcd, 0xf6, 0xe9, 0x6e, 0x38, 0x1b, 0xd9, 0xe7, 0x71, 0xf7, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0x44, 0x2a, 0xb4, 0xf9, 0x43, 0x02, 0x00, 0x00,
}
