// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accbase/srv/auth/proto/auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61feb0de52e706d0, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61feb0de52e706d0, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RegisterRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	VerifyPassword       string   `protobuf:"bytes,4,opt,name=verifyPassword,proto3" json:"verifyPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61feb0de52e706d0, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetVerifyPassword() string {
	if m != nil {
		return m.VerifyPassword
	}
	return ""
}

type RegisterResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61feb0de52e706d0, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserInfoRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoRequest) Reset()         { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()    {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61feb0de52e706d0, []int{4}
}

func (m *UserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRequest.Unmarshal(m, b)
}
func (m *UserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRequest.Marshal(b, m, deterministic)
}
func (m *UserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRequest.Merge(m, src)
}
func (m *UserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoRequest.Size(m)
}
func (m *UserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRequest proto.InternalMessageInfo

func (m *UserInfoRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserInfoResponse struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61feb0de52e706d0, []int{5}
}

func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (m *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(m, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type RoleRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleRequest) Reset()         { *m = RoleRequest{} }
func (m *RoleRequest) String() string { return proto.CompactTextString(m) }
func (*RoleRequest) ProtoMessage()    {}
func (*RoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61feb0de52e706d0, []int{6}
}

func (m *RoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleRequest.Unmarshal(m, b)
}
func (m *RoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleRequest.Marshal(b, m, deterministic)
}
func (m *RoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleRequest.Merge(m, src)
}
func (m *RoleRequest) XXX_Size() int {
	return xxx_messageInfo_RoleRequest.Size(m)
}
func (m *RoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoleRequest proto.InternalMessageInfo

func (m *RoleRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RoleResponse struct {
	Roles                string   `protobuf:"bytes,1,opt,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleResponse) Reset()         { *m = RoleResponse{} }
func (m *RoleResponse) String() string { return proto.CompactTextString(m) }
func (*RoleResponse) ProtoMessage()    {}
func (*RoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61feb0de52e706d0, []int{7}
}

func (m *RoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleResponse.Unmarshal(m, b)
}
func (m *RoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleResponse.Marshal(b, m, deterministic)
}
func (m *RoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleResponse.Merge(m, src)
}
func (m *RoleResponse) XXX_Size() int {
	return xxx_messageInfo_RoleResponse.Size(m)
}
func (m *RoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoleResponse proto.InternalMessageInfo

func (m *RoleResponse) GetRoles() string {
	if m != nil {
		return m.Roles
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "auth.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "auth.LoginResponse")
	proto.RegisterType((*RegisterRequest)(nil), "auth.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "auth.RegisterResponse")
	proto.RegisterType((*UserInfoRequest)(nil), "auth.UserInfoRequest")
	proto.RegisterType((*UserInfoResponse)(nil), "auth.UserInfoResponse")
	proto.RegisterType((*RoleRequest)(nil), "auth.RoleRequest")
	proto.RegisterType((*RoleResponse)(nil), "auth.RoleResponse")
}

func init() { proto.RegisterFile("accbase/srv/auth/proto/auth.proto", fileDescriptor_61feb0de52e706d0) }

var fileDescriptor_61feb0de52e706d0 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xdd, 0x4e, 0x32, 0x41,
	0x0c, 0x65, 0xbf, 0x8f, 0x35, 0x58, 0x51, 0xb0, 0xa2, 0x21, 0x7b, 0xa5, 0xe3, 0x1f, 0x57, 0x60,
	0xf0, 0xd2, 0x2b, 0x6f, 0x4c, 0x4c, 0x8c, 0x31, 0x9b, 0xf8, 0x00, 0x03, 0x16, 0xd8, 0x08, 0x3b,
	0x38, 0x9d, 0xc5, 0xf8, 0x04, 0xbe, 0xa9, 0xcf, 0x61, 0x98, 0xd9, 0x71, 0x61, 0x63, 0x88, 0x77,
	0x3d, 0x9d, 0xd3, 0xd3, 0xd3, 0x76, 0xe0, 0x44, 0x0e, 0x87, 0x03, 0xc9, 0xd4, 0x63, 0xbd, 0xe8,
	0xc9, 0xcc, 0x4c, 0x7a, 0x73, 0xad, 0x8c, 0xb2, 0x61, 0xd7, 0x86, 0x58, 0x5d, 0xc6, 0xe2, 0x0e,
	0xea, 0x0f, 0x6a, 0x9c, 0xa4, 0x31, 0xbd, 0x65, 0xc4, 0x06, 0x23, 0xa8, 0x65, 0x4c, 0xfa, 0x51,
	0xce, 0xa8, 0x1d, 0x1c, 0x07, 0x9d, 0xed, 0xf8, 0x07, 0x2f, 0xdf, 0xe6, 0x92, 0xf9, 0x5d, 0xe9,
	0x97, 0xf6, 0x3f, 0xf7, 0xe6, 0xb1, 0x38, 0x87, 0xdd, 0x5c, 0x87, 0xe7, 0x2a, 0x65, 0xc2, 0x16,
	0x84, 0x46, 0xbd, 0x52, 0x9a, 0xab, 0x38, 0x20, 0x3e, 0x03, 0x68, 0xc4, 0x34, 0x4e, 0xd8, 0x90,
	0xfe, 0x4b, 0xcb, 0x16, 0x84, 0x34, 0x93, 0xc9, 0x34, 0xef, 0xe7, 0xc0, 0x9a, 0x91, 0xff, 0xeb,
	0x46, 0xf0, 0x02, 0xf6, 0x16, 0xa4, 0x93, 0xd1, 0xc7, 0x93, 0x67, 0x54, 0x2d, 0xa3, 0x94, 0x15,
	0x1d, 0x68, 0x16, 0x46, 0x36, 0x7a, 0xbe, 0x84, 0xc6, 0x33, 0x93, 0xbe, 0x4f, 0x47, 0xca, 0x5b,
	0xfe, 0x9d, 0xd8, 0x85, 0x66, 0x41, 0xcc, 0x25, 0x37, 0x0c, 0x27, 0x4e, 0x61, 0x27, 0x56, 0x53,
	0xda, 0x2c, 0x7a, 0x06, 0x75, 0x47, 0x2a, 0x3c, 0x6a, 0x35, 0x25, 0xf6, 0x2c, 0x0b, 0xfa, 0x5f,
	0x01, 0x54, 0x6f, 0x33, 0x33, 0xc1, 0x3e, 0x84, 0xf6, 0x0e, 0x88, 0x5d, 0x7b, 0xeb, 0xd5, 0xe3,
	0x46, 0x07, 0x6b, 0x39, 0x27, 0x28, 0x2a, 0x78, 0x03, 0x35, 0xbf, 0x0a, 0x3c, 0x74, 0x94, 0xd2,
	0x8d, 0xa2, 0xa3, 0x72, 0x7a, 0xb5, 0xd8, 0x0f, 0xed, 0x8b, 0x4b, 0xdb, 0xf2, 0xc5, 0xe5, 0xdd,
	0x88, 0x0a, 0x5e, 0x41, 0xb8, 0x1c, 0x8e, 0x71, 0x3f, 0xd7, 0x2f, 0xd6, 0x11, 0xe1, 0x6a, 0xca,
	0x57, 0x0c, 0xb6, 0xec, 0xe7, 0xbd, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x4a, 0x59, 0xaa,
	0xe1, 0x02, 0x00, 0x00,
}
